### ISSUE TITLE
Info window stopped working

### ISSUE THREAD

**Issue by justanerik** [hudiniq/mui#1]
I love this UI for MUME!  In the last day, the info window stopped working.  It's just black with no content.

**Comment by hudiniq** [comment]
Thanks, I'm glad you find it useful.
I tested it on my end and it works when I log in or re-log. Can you please have a look in Mudlet's error console and paste any errors here, so I see what's disturbing it?

Sorry, I'm just gonna preemptively describe where you find the error console, just in case.
In the editor window (the window where you have your triggers, aliases, scripts, ...) you have a button labeled "Errors" on the left.

**Comment by justanerik** [comment]
It worked and have no idea what the issue was yesterday, since I restarted Mudlet a few times and no profile changes since then.  If it stops working again, I'll try to capture the errors.  Thanks!
